#!/bin/bash

# foobar2000 env
progName=foobar2000
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe
# progUiFix=$progHome/configuration/foo_ui_std.dll.cfg

if [ ! -d $progHome ];then
ensure_dir_exists $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null

# fix ui glitch - workaround bug ui not showing of foobar2000 on wine.
# if [ -f $progUiFix ]; then
# rm "$progUiFix"
# fi
