name: foobar2000
title: foobar2000 (WINE)
summary: foobar2000 is an advanced freeware audio player.
description: |
 Features
   *Supported audio formats are MP3, MP4, AAC, CD Audio, WMA, Vorbis, Opus, FLAC, WavPack, WAV, AIFF, Musepack, Speex, AU, SND... and more with additional components.
   *Gapless playback.
   *Easily customizable user interface layout.
   *Advanced tagging capabilities.
   *Support for ripping Audio CDs as well as transcoding all supported audio formats using the Converter component.
   *Full ReplayGain support.
   *Customizable keyboard shortcuts.
   *Open component architecture allowing third-party developers to extend functionality of the player.
adopt-info: foobar2000

confinement: strict
grade: stable
architectures:
  - build-on: amd64
base: core22
compression: lzo

plugs:
  shmem:
    interface: shared-memory
    private: true
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-9-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-9-devel-core22

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="  # Prevent pop-ups about Wine Mono and Wine Gecko
  WINEARCH: "win32"
  TRICKS: "wmp9 vcrun2017"
  RUN_EXE: "$SNAP_USER_DATA/foobar2000/foobar2000.exe"
  SOMMELIER_KEEP_CWD: "1"  # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1"  # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1"  # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  SOMMELIER_NO_THEME: 1

apps:
  foobar2000:
    extensions: [gnome]
    command: bin/sommelier run-exe
    plugs:
      - audio-playback
      - home
      - network
      - cups-control
      - removable-media
      - optical-drive
      - shmem
    desktop: usr/share/applications/foobar2000.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [gnome]
    command: bin/sommelier
    plugs:
      - home
      - network
      - cups-control
      - removable-media
      - shmem
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [gnome]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  foobar2000:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default
      set -ex
      ver=$(wget http://www.foobar2000.org/download -q -S -O - 2>&1 | grep -Eo v[0-9].* | sed 's|v||;s|.exe| |g' | awk '{print $1}' | head -1)
      snapcraftctl set-version "$ver"
      ./dl_f2k
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "core22"
    build-packages:
      - libc6-dev-i386
      - gcc-multilib
